import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "./components/BottomNav";
import SplashGate from "./components/SplashGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hackathon Doctolib",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/icon_blue.png",
    shortcut: "/icons/icon_blue.png",
    apple: "/icons/icon_blue.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SplashGate />
        <div className="pb-20 md:pb-0">{children}</div>
        <BottomNav />
      </body>
    </html>
  );
}
